### ISSUE TITLE
Missing "SWIFT_VERSION" upon pod install

### ISSUE THREAD

**Issue by feudadrien** [n1k3c/flutter-link-preview#1]
After doing "pod install"

I get this

**[!] Unable to determine Swift version for the following pods:

`link_preview` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.**

Any help

**Comment by n1k3c** [comment]
@feudadrien I just updated the library to `0.1.4`, it should work now.

**Comment by Shakle** [comment]
Sorry, but 0.1.4 and 0.1.5 continue to show this:
    - `link_preview` does not specify a Swift version and none of the targets (`Runner`) integrating it have the `SWIFT_VERSION` attribute set. Please contact the author or set the `SWIFT_VERSION` attribute in at least one of the targets that integrate this pod.
